spring.application.name=backend

# Database Configuration
# spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
# spring.datasource.username=postgres
# # spring.datasource.password=root

# server.port=${PORT:8080}
# spring.datasource.url=jdbc:${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

# # spring.datasource.url= postgresql://task_db_a4fs_user:hsq5Py6JKfr19CeW7EliifcsIMg6fhyc@dpg-d8648u7dl75s739e98q0-a/task_db_a4fs
# # spring.datasource.username=task_db_a4fs_user
# # spring.datasource.password=hsq5Py6JKfr19CeW7EliifcsIMg6fhyc
# spring.datasource.driver-class-name=org.postgresql.Driver

# # JPA Configuration
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.format_sql=true

# # Logging Configuration
# logging.level.org.springframework.security=INFO
# logging.level.org.springframework.web=INFO
# logging.level.org.hibernate.SQL=DEBUG

# # JWT Security Configuration
# application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# application.security.jwt.expiration=86400000

server.port=${PORT:8080}

spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true